import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AmplifyClientSide from "./AmplifyClient";
import "@aws-amplify/ui-react/styles.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Partyho",
  description: "Generated by partyho",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AmplifyClientSide>{children}</AmplifyClientSide>
      </body>
    </html>
  );
}
